#!/usr/bin/env node
/* Regenerates catalog/ from the installed @12-apps/ui.
   The catalog is generated because hand-writing 128 import paths is how a
   wrong name gets into the specification. */
const fs = require("fs");
const path = require("path");

const pkgPath = require.resolve("@12-apps/ui/package.json", { paths: [process.cwd()] });
const pkg = require(pkgPath);
const out = path.join(__dirname, "..", "catalog");

const rows = Object.keys(pkg.exports || {})
  .filter(k => k !== ".")
  .map(k => {
    const parts = k.split("/");
    return { name: parts[parts.length - 1], group: parts[1], imp: "@12-apps/ui" + k.slice(1) };
  });

const cat = {};
rows.forEach(r => { if (!cat[r.name]) cat[r.name] = r.imp; });

fs.writeFileSync(path.join(out, "ui-catalog.js"),
  `/* Catalog of @12-apps/ui@${pkg.version} — generated by scripts/generate-catalog.js.\n`
  + `   ${Object.keys(cat).length} components. Do not edit by hand. */\n`
  + `window.PROTO_UI = ${JSON.stringify(cat, null, 2)};\n`);

const byGroup = {};
rows.forEach(r => (byGroup[r.group] = byGroup[r.group] || []).push(r));
let md = `# @12-apps/ui@${pkg.version} — catalog\n\nGenerated from package.json. ${rows.length} entries.\n`;
Object.keys(byGroup).sort().forEach(g => {
  md += `\n## ${g}\n\n`;
  byGroup[g].sort((a, b) => a.name.localeCompare(b.name))
    .forEach(r => { md += `- \`${r.name}\` — \`${r.imp}\`\n`; });
});
fs.writeFileSync(path.join(out, "ui-catalog.md"), md);

console.log(`catalog generated: ${Object.keys(cat).length} components from @12-apps/ui@${pkg.version}`);
console.log("note: ui-interactions.* is a curated classification — review it by hand when the lib changes.");
